[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.hover_tilt = self.hover_tilt/1.5"
position = "after"
payload = '''
elseif self.ability.name == "Blank Joker" then
    scale_mod = -0.5
    self.hover_tilt = self.hover_tilt*1.5
    self.children.floating_sprite:draw_shader('dissolve',0, nil, nil, self.children.center,scale_mod, rotate_mod,nil, 0.1 + 0.03*math.sin(1.8*G.TIMERS.REAL),nil, 0.6)
    self.children.floating_sprite:draw_shader('hologramv2', nil, self.ARGS.send_to_shader, nil, self.children.center, scale_mod, rotate_mod)
    self.hover_tilt = self.hover_tilt/1.5
'''
match_indent = true